#!/sbin/runscript
# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	need net
	use logger
}

start() {
	ebegin "Starting IGMPproxy"
	start-stop-daemon --start --background \
		--make-pidfile --pidfile /var/run/igmpproxy.pid \
		--exec /usr/bin/igmpproxy -- "${IGMPPROXY_CONFIG}"
	eend $?
}

stop() {
	ebegin "Stopping IGMPproxy"
	start-stop-daemon --stop --pidfile /var/run/igmpproxy.pid
	eend $?
}
