#!/sbin/runscript

PIDFILE="/var/run/${SVCNAME}.pid"

depend() {
	need localmount
}

start() {
	ebegin "Starting ${SVCNAME}"
	start-stop-daemon --start --user "${RFSD_USER:-root}" \
		--make-pidfile --pidfile "${PIDFILE}" --background \
		--name "${SVCNAME}" --exec /usr/bin/rfsd -- \
		"${RFSD_HOST}" "${RFSD_PORT}"
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --pidfile "${PIDFILE}" --retry TERM/2/KILL
	eend $?
}
