#!/sbin/runscript

depend() {
	need net
}

start() {
	ebegin "Starting eserver"
	/sbin/start-stop-daemon --start \
		--chdir "${ESERVER_DIR}" --chuid "${ESERVER_UID}" \
		--make-pidfile --pidfile /var/run/eserver.pid --background \
		--exec /usr/bin/eserver-launch -- /usr/bin/eserver
	eend $?
}

stop() {
	ebegin "Stopping eserver"
	start-stop-daemon --stop \
		--pidfile /var/run/eserver.pid --retry INT/2/KILL
	eend $?
}
